-- Arquivo de criação
-- do banco de dados

-- COMANDOS SQL SE DIVIDEM EKM DUAS LINGUAGENS
-- DDL(data Definition Languagem)
-- Comandos de definição do banco de dados
-- Ex: CREATE DATABASE NAME
--     DROP DATABASE NAME
--   CREATE TABLE NAME(COLUNAS)
--      DROP TABLE NAME
-- --------------------------------------------
--  DML (DATA MANIPULATION LANGUAGE)
-- == COMANDOS DE MANIPULAÇAO DE DADOS
-- eX: SELECT COLUNAS FROM TABELA
--     INSERT INTO TABELA (COLUNAS) VALUES (VALORES)
--     DELETE FROM TABELA
--     UPDATE COLUNAS FROM TABELA